[project]
name = "ecom-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-cohere>=0.5.0",
    "pydantic>=2.12.5",
    "pyodbc>=5.3.0",
    "sqlglot>=28.10.1",
]
